name: MPI & Pthread CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install MPI and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mpich libmpich-dev g++ cmake

      - name: Compile MPI & Pthread Program
        run: |
          mpic++ -o main.out main.cpp -pthread

      - name: Run MPI Program with 4 Processes
        run: |
          mpirun -np 4 ./main.out
